spring:
    profiles: 
        active:
        - dev

---
spring:
    profiles: dev
    appplication:
        name: config-dev

---
spring:
    profiles: test
    application:
        name: config-test